import { useEffect, useRef } from 'react';
export default function HackerEffects({motion}:{motion:boolean}){
  const canvas=useRef<HTMLCanvasElement>(null);const pointer=useRef<HTMLDivElement>(null);const progress=useRef<HTMLDivElement>(null);
  useEffect(()=>{let frame=0;const update=()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;const distance=document.documentElement.scrollHeight-window.innerHeight;progress.current?.style.setProperty('transform',`scaleX(${distance>0?Math.min(1,window.scrollY/distance):0})`);});};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update);};},[]);
  useEffect(()=>{if(!motion||!matchMedia('(pointer:fine)').matches)return;let frame=0;let current:HTMLElement|null=null;let latest:PointerEvent|null=null;
    const move=(e:PointerEvent)=>{latest=e;if(frame)return;frame=requestAnimationFrame(()=>{frame=0;if(!latest)return;const {clientX:x,clientY:y}=latest;pointer.current?.style.setProperty('transform',`translate3d(${x}px,${y}px,0)`);pointer.current?.classList.add('visible');const target=(latest.target as HTMLElement).closest<HTMLElement>('.project-card,.service-card,.note-card,.portrait-frame,.button,.github-panel,.contact-form');if(current!==target){current?.style.removeProperty('--rx');current?.style.removeProperty('--ry');current?.removeAttribute('data-hovered');current=target;}if(target){const r=target.getBoundingClientRect();target.style.setProperty('--mx',`${x-r.left}px`);target.style.setProperty('--my',`${y-r.top}px`);target.style.setProperty('--rx',`${-(y-r.top-r.height/2)/r.height*5}deg`);target.style.setProperty('--ry',`${(x-r.left-r.width/2)/r.width*5}deg`);target.dataset.hovered='true';}pointer.current?.classList.toggle('over-control',!!(latest.target as HTMLElement).closest('button,a,input,select,textarea'));});};
    const leave=()=>{pointer.current?.classList.remove('visible');current?.removeAttribute('data-hovered');current=null;};window.addEventListener('pointermove',move,{passive:true});document.documentElement.addEventListener('pointerleave',leave);window.addEventListener('blur',leave);return()=>{cancelAnimationFrame(frame);window.removeEventListener('pointermove',move);document.documentElement.removeEventListener('pointerleave',leave);window.removeEventListener('blur',leave);leave();};
  },[motion]);
  useEffect(()=>{const c=canvas.current;if(!c||!motion)return;const ctx=c.getContext('2d');if(!ctx)return;let w=0,h=0,drops:number[]=[],frame=0,last=0;const resize=()=>{w=c.clientWidth;h=c.clientHeight;c.width=w;c.height=h;drops=Array.from({length:Math.ceil(w/24)},()=>Math.random()*-50);};resize();const ro=new ResizeObserver(resize);ro.observe(c);const chars='01{}<>/;:ABCDEF';const render=(time:number)=>{frame=requestAnimationFrame(render);if(time-last<80||document.hidden)return;last=time;ctx.fillStyle='rgba(12,7,20,.12)';ctx.fillRect(0,0,w,h);ctx.font='12px monospace';drops.forEach((y,i)=>{ctx.fillStyle=i%5===0?'#eda3f3':'#b788f5';ctx.fillText(chars[Math.floor(Math.random()*chars.length)],i*24,y*22);if(y*22>h&&Math.random()>.98)drops[i]=-5;else drops[i]+=.45;});};frame=requestAnimationFrame(render);return()=>{cancelAnimationFrame(frame);ro.disconnect();ctx.clearRect(0,0,w,h);};},[motion]);
  return <><div ref={progress} className="reading-progress" aria-hidden="true"/><canvas ref={canvas} className="matrix-backdrop" aria-hidden="true"/><div ref={pointer} className="pointer-halo" aria-hidden="true"><div/><span/></div></>;
}
